# A sample Gemfile
source "http://rubygems.org"
gem 'sinatra'
gem 'rack'
gem 'rack-session-stack'
gem 'activerecord'
gem 'unicorn'
gem 'rails'
gem 'mysql'
gem 'platform_helpers'
gem 'wait_for'
gem 'warden'
