#!/bin/sh
/usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --user=mysql --pid-file=/var/run/mysqld/mysqld.pid --skip-external-locking --socket=/var/run/mysqld/mysqld.sock --port=6000 --bind=127.0.0.1 &
