# Authod: Cliff Cyphers
# Published as part of the cyberconnect's platform mainly used
# in hosting rails applications.  
# Licesnse: GPLv3: http://www.gnu.org/licenses/gpl.html


:copy_items:
- /bin/chmod
- /bin/chown
- /bin/true
:depends_on:
- <update path for where you have phased_layer_tunnel>/config/ubuntu_10.04_sshd.yaml

